### ISSUE TITLE
Make your first release

### ISSUE THREAD

**Issue by diogobernini** [einaregilsson/InsertIcons#4]
You should release the executable files under the release section, it might make it easier for people who won't change the source.

**Comment by einaregilsson** [comment]
The release section on github only allows tags of the repository, not uploading arbitrary files. Having said that, there's a link to a .exe download from the blog post: http://einaregilsson.com/add-multiple-icons-to-a-dotnet-application/

**Comment by einaregilsson** [comment]
Ok, well that was wrong, I looked more into it and you can attach binaries. Have made a release for 1.1:

https://github.com/einaregilsson/InsertIcons/releases/tag/1.1

**Comment by diogobernini** [comment]
Yes, you can attach as a release. Thanks!
