### ISSUE TITLE
[RELEASE] .NET 4.6.1 Fork

### ISSUE THREAD

**Issue by ghost** [einaregilsson/InsertIcons#6]
To any who see this,

I have created a fork of InsertIcons which has a simple to use GUI that runs on the latest .NET Framework (4.6.1 as of the time this was written) and is available here: https://github.com/ntegrl/XInject

Hopefully this will help out anyone in need of injecting icons into their assemblies and I also wish to thank Einar for his original contribution.

— Integral

**Comment by niemyjski** [comment]
This repo is no longer valid
